site_name: Less-Than-10 Tutorials (<10)

theme: 
    name: readthedocs # material
    highlightjs: true  # only for readthedocs


site_url: https://towshif.github.io


extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
      

# markdown_extensions:
#   - codehilite
